name: graphica
description: Graphica game
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flame:
    ^1.28.0

    # Localizations
  intl: ^0.19.0
  slang: ^4.4.1
  slang_flutter: ^4.4.0

  # Navigation
  go_router: ^15.1.1

  # Ui
  cupertino_icons: ^1.0.8
  balanced_text: ^0.0.3
  shimmer_effect: ^1.0.4
  flutter_svg: ^2.0.10+1
  flutter_colorpicker: ^1.1.0
  auto_size_text: ^3.0.0
  modal_bottom_sheet: ^3.0.0
  fl_chart: ^0.71.0
  loading_animation_widget: ^1.2.0+4
  animated_text_kit: ^4.2.2
  flutter_masked_text2: ^0.9.1
  google_fonts: ^6.2.1

  # DI
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  dropdown_button2: ^3.0.0-beta.9

  # State management
  flutter_bloc: ^9.0.0
  flutter_hooks: ^0.21.2

  # Model serialization
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Features
  is_first_run: ^1.0.0
  shared_preferences: ^2.2.3
  device_preview: ^1.2.0
  flutter_native_splash: ^2.4.3
  pinput: ^5.0.1
  url_launcher: ^6.3.1
  animations: ^2.0.11
  infinite_scroll_pagination: ">=4.1.0 <5.0.0"
  package_info_plus: ^8.0.0
  faker: ^2.2.0

  # Api
  chopper: ^8.0.3
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  cupertino_back_gesture: ^0.1.0
  theme_tailor: ^3.0.1
  theme_tailor_annotation: ^3.0.1
  text_balancer: ^0.1.6
  biometric_storage: ^5.1.1-dev.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.9
  chopper_generator: ^8.0.3
  slang_build_runner: ^4.4.2

  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
